swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /director:
    get:
      operationId: director.read_all
      tags:
        - Director
      summary: Read the entire set of director, sorted by id
      description: Read the entire set of director, sorted by id
      responses:
        200:
          description: Successfully read director set operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  description: Id of the director
                name:
                  type: string
                  description: Name of the director
                gender:
                  type: integer
                  description: Gender of the director
                uid:
                  type: integer
                  description: Uid of the director
                department:
                  type: string
                  description: Department of the director

    post:
      operationId: director.create
      tags:
        - Director
      summary: Create a director
      description: Create a new director
      parameters:
        - name: dir
          in: body
          description: Director to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of director to create
              gender:
                type: integer
                description: Gender of director to create
              uid:
                type: integer
                description: Uid of director to create
              department:
                type: string
                description: Name of director to create
      responses:
        201:
          description: Successfully created director
          schema:
            properties:
              id:
                type: integer
                description: ID of created director
              name:
                type: string
                description: Name of created director
              gender:
                type: integer
                description: Gender of created director
              uid:
                type: integer
                description: Uid of created director
              department:
                type: string
                description: Name of created director